env:
- PLATFORM=debian-wheezy
- PLATFORM=debian-jessie

install:
- curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
- ./run 'docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run --name $PLATFORM test-$PLATFORM'
