env:
  - PLATFORM='docker-debian-jessie'  ANSIBLE_VERSION='ansible>=2.5,<2.6'
  - PLATFORM='docker-debian-stretch' ANSIBLE_VERSION='ansible>=2.5,<2.6'
  - PLATFORM='docker-debian-buster'  ANSIBLE_VERSION='ansible>=2.5,<2.6'
  - PLATFORM='docker-ubuntu-bionic'  ANSIBLE_VERSION='ansible>=2.5,<2.6'
  - PLATFORM='docker-debian-jessie'  ANSIBLE_VERSION='ansible>=2.6,<2.7'
  - PLATFORM='docker-debian-stretch' ANSIBLE_VERSION='ansible>=2.6,<2.7'
  - PLATFORM='docker-debian-buster'  ANSIBLE_VERSION='ansible>=2.6,<2.7'
  - PLATFORM='docker-ubuntu-bionic'  ANSIBLE_VERSION='ansible>=2.6,<2.7'
  - PLATFORM='docker-debian-jessie'  ANSIBLE_VERSION='ansible>=2.7,<2.8'
  - PLATFORM='docker-debian-stretch' ANSIBLE_VERSION='ansible>=2.7,<2.8'
  - PLATFORM='docker-debian-buster'  ANSIBLE_VERSION='ansible>=2.7,<2.8'
  - PLATFORM='docker-ubuntu-bionic'  ANSIBLE_VERSION='ansible>=2.7,<2.8'
  - PLATFORM='docker-debian-jessie'  ANSIBLE_VERSION='ansible>=2.8,<2.9'
  - PLATFORM='docker-debian-stretch' ANSIBLE_VERSION='ansible>=2.8,<2.9'
  - PLATFORM='docker-debian-buster'  ANSIBLE_VERSION='ansible>=2.8,<2.9'
  - PLATFORM='docker-ubuntu-bionic'  ANSIBLE_VERSION='ansible>=2.8,<2.9'
  - PLATFORM='docker-debian-jessie'  ANSIBLE_VERSION='ansible>=2.9,<2.10'
  - PLATFORM='docker-debian-stretch' ANSIBLE_VERSION='ansible>=2.9,<2.10'
  - PLATFORM='docker-debian-buster'  ANSIBLE_VERSION='ansible>=2.9,<2.10'
  - PLATFORM='docker-ubuntu-bionic'  ANSIBLE_VERSION='ansible>=2.9,<2.10'

sudo: required

dist: trusty

language: python
python:
  - 2.7
  - 3.6

services:
  - docker

before_install:
  - wget https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb
  - sudo dpkg -i vagrant_2.0.1_x86_64.deb

install:
  - pip install "$ANSIBLE_VERSION"

script:
  - VAGRANT_DEFAULT_PROVIDER=docker vagrant up $PLATFORM
  - >
    VAGRANT_DEFAULT_PROVIDER=docker vagrant provision $PLATFORM
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - VAGRANT_DEFAULT_PROVIDER=docker vagrant status

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
