---

- name: LOCALE | Add
  locale_gen: name={{ item }} state=present
  with_items: "{{ dbs_locales }}"

- name: TEMPLATE | Deploy default locale
  template: src=etc/default/locale.j2 dest=/etc/default/locale

- name: LINEINFILE | Uncomment necessary lines in /etc/locale.gen
  lineinfile: >
    dest=/etc/locale.gen
    regexp="^# ({{ item }}) (.*)$"
    line="{{ item }} \1"
    backrefs=yes
  with_items: "{{ system_locales }}"
  notify: locale-gen
